query ApiJobPosting($organizationHostedJobsPageName: String!, $jobPostingId: String!) { jobPosting(organizationHostedJobsPageName: $organizationHostedJobsPageName, jobPostingId: $jobPostingId) { id title departmentName departmentExternalName locationName locationAddress workplaceType employmentType descriptionHtml isListed isConfidential teamNames recaptchaAction applicationForm { ...FormRenderParts } surveyForms { ...FormRenderParts } secondaryLocationNames compensationTierSummary compensationTiers { id title tierSummary } applicationDeadline compensationTierGuideUrl scrapeableCompensationSalarySummary compensationPhilosophyHtml applicationLimitCalloutHtml shouldAskForTextingConsent shouldAskForWhatsAppConsent candidateTextingPrivacyPolicyUrl candidateTextingTermsAndConditionsUrl legalEntityNameForTextingConsent automatedProcessingLegalNotice { automatedProcessingLegalNoticeRuleId automatedProcessingLegalNoticeHtml } } }
fragment JSONBoxParts on JSONBox { value }
fragment FileParts on File { id filename }
fragment FormFieldEntryParts on FormFieldEntry { id field fieldValue { ... on JSONBox { ...JSONBoxParts } ... on File { ...FileParts } ... on FileList { files { ...FileParts } } } isRequired descriptionHtml isHidden }
fragment FormRenderParts on FormRender { id formControls { identifier title } errorMessages formErrors { message fieldEntryId } sections { title descriptionHtml fieldEntries { ...FormFieldEntryParts } isHidden } sourceFormDefinitionId }
